### ISSUE TITLE
Unexpected double closed comment section

### ISSUE THREAD

**Issue by tilya2014** [btamburrino/VSCode-Apex-Javadoc#6]
When I type /** and press tab javadoc comment sections is generated as expected. But in the end I see duplicated comment closing (*/). 
example:
	/**
	 * retrieveRecordsByRecordID description
	 * @param  recordIDs recordIDs description
	 * @return           return description
	 */ */

**Comment by shanekenyon87** [comment]
Same.

**Comment by shanekenyon87** [comment]
@btamburrino I will fork and fix this.  Will you accept the merge and republish the extension?

**Comment by btamburrino** [comment]
@shanekenyon87 I actually have a fix locally, but one thing I did notice is that it happens for VSCode on one machine but not the other. I was planning on having it be a settings toggle so it wouldn't break things people who don't see this issue.

I actually have to try to remember how to publish to the VSCode Marketplace. Haven't logged in since the initial release of this.

**Comment by btamburrino** [comment]
I've figured out all my old credentials and pushed 1.1.0 with this fix to the Marketplace and was able to update my extension.

The new User Setting `force.showApexJavadocTrailingCloseComment` defaults to true (which is the bug) - just set this to false and the duplicate `*/` will no longer appear.

**Comment by shanekenyon87** [comment]
Thanks man!  I reinstalled 1.1.0 and set that value to false but am still getting the double quote.  I'll try restarting VSCode and see what happens.

**Comment by btamburrino** [comment]
@shanekenyon87 I updated the extension via the extension manager in both my Windows and Mac machines and was able to get it to work with that value being false.

The underlying issue is that some other plugin (either the Salesforce Extension Pack or perhaps even VSCode itself) is also putting in a `*/`, something it wasn't doing when I initially developed this in 2017. For a while, it wasn't happening on my Mac and only my Windows machine, so I thought it might have been because of a different configuration on the two systems. That's why I didn't wholesale remove the `*/` and instead made it a configuration option.

Is it possible that you're running a local version of the extension that you forked? I know I've done that unknowingly a few times.

**Comment by shanekenyon87** [comment]
@btamburrino I did not actually do anything with the fork yet other than clone it.  Is 1.1 the correct version?

**Comment by btamburrino** [comment]
@shanekenyon87  Yes, 1.1.0 is the correct version.

Use the gear icon on the extension pane to see the actual settings and make sure that the new one is set to false. If it still does it, then I'm beginning to think that some other extension might be adding it in. I tested it on two different systems on two different OS's and the fix worked as intended.

As a last resort workaround, you can find the installed extension code and just comment out the line that adds the trailing `*/` to the `comment` variable. It'll stay that way until I push a new update which obviously won't be very often. (It's what I did when I thought it was just a me issue!)

**Comment by shanekenyon87** [comment]
I suspect you are right, I will double check what other extensions are installed.  The change I was going to make on my fork was to look at the output and replace `*/ */` with `*/`.  But that may not work if the second `*/` is being appended after your code runs.

**Comment by shanekenyon87** [comment]
@btamburrino It works correctly when I right click and execute `Force: Stub Apex Javadoc Comment` but when I type `/**` then Tab, it is still adding the second `*/`.  I don't have any other documentation plug-ins installed.  Anyhow, thought you'd find this of interest.

**Comment by btamburrino** [comment]
@shanekenyon87 All that really tells me is that, for whatever reason, your version of the extension is ignoring the new flag. If it was working, when you used the right click, it would give you an incomplete javadoc.

You're positive that your settings screen looks like this?
![ApexJavadocSettings](https://user-images.githubusercontent.com/1213692/81854838-8030c180-952c-11ea-8289-9b896143fcb9.jpg)

**Comment by shanekenyon87** [comment]
OK, it is now, and it works!  Thanks!  I guess the wording for that setting threw me off a bit, sorry about that.  Here is what my settings are now:

```{
    "salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home",
    "files.autoSaveDelay": 5000,
    "salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true,
    "force.showApexJavadocContext": true,
    "editor.tabSize": 2,
    "editor.renderWhitespace": "all",
    "[apex]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnPaste": true,
    "workbench.settings.useSplitJSON": true,
    "workbench.settings.editor": "json",
    "prettier.resolveGlobalModules": true,
    "force.showApexJavadocTrailingCloseComment": false
}
```

**Comment by shanekenyon87** [comment]
@btamburrino I have some updates, with the settings suggested as above, here are my results:

- `/*` Before method definition: Adds single `*/` (WORKS)
- `/*` Before class definition: Adds double `*/ */` (BUG)
- Right click method `Force: Stub Apex Javadoc Comment`: Add NO closing comment (BUG)
