### ISSUE TITLE
Feature Request: Configurable @ annotations.

### ISSUE THREAD

**Issue by codefriar** [btamburrino/VSCode-Apex-Javadoc#8]
I would love a way to configure which @ annotations are included in the apex doc block. Specifically, I'd like to be able to *disable* the @author line.

**Comment by jonathanwiesel** [comment]
Adding to this, in order to comply with [PMD's ApexDoc rules](https://pmd.github.io/latest/pmd_rules_apex_documentation.html), it will be great if one would be able to configure the `@description` annotation

**Comment by btamburrino** [comment]
This bump made me go into a deeper look and found an ApexDocs npm library (since Salesforce discontinued the Java app I was using years ago when I first made this) so I'll try to work on putting in the `@description` decorator over the next week or so.

That being said, I don't add the `@author` line, so that might be a different plugin?

**Comment by ScriptMonkey00** [comment]
@btamburrino Actually we're just looking at formalizing our documentation format to match ApexDoc at my place of business and the only reason we're not using your tool was the missing @description so I'd love if that was updated and dropped in.

Thanks for making this tool! (I especially love the hovers that show the documentation block!)

**Comment by ScriptMonkey00** [comment]
@btamburrino Just wanted to offer to swap out the order on the description myself since it's a pretty simple change, then you could PR it and merge it into the published extension when you can.

**Comment by btamburrino** [comment]
@ScriptMonkey00 I had some other updates that I wanted to throw in and, honestly, trying to remember how to publish to the VSCode Marketplace takes up most of my time since I don't do it often. I also wanted to make the tag configurable in terms of being turned on or off so I didn't want to just add it to the string verbatim.

I just pushed 1.2.0 up to the marketplace so it should propagate throughout the day.

**Comment by ScriptMonkey00** [comment]
@btamburrino Fantastic, thanks!  I hope you didn't take my offer as pressure or harassment! :) I actually meant to just offer my help.  I appreciate your volunteered time.

**Comment by btamburrino** [comment]
@ScriptMonkey00 Honestly, it was just fortuitous timing - the dreaded bucket truck was in my neighborhood and had to take down the cable line for an hour and a half or so. I could no longer work on the cloud, so I spent that time working locally on this extension and my internet came back up right when I was done.
